### ISSUE TITLE
Can't give input to shell programs that expect input

### ISSUE THREAD

**Issue by The-J-Person** [thedaniel/terminal-panel#10]
Example:
grep cookie
At that moment that specific terminal tab locks up, but I want to type things?

**Comment by aeberlin** [comment]
Also occurs when doing ruby development and using the `irb` command :+1:

**Comment by sedabull** [comment]
I've looked through the source code and the reason for this issue is located in lib/command-output-view.coffee `CommandOutputView::spawn`. It seems that originally `child_process.spawn` was used to execute a command, but now its done using `child_process.exec`. This is certainly much simpler, but that simplicity comes at the cost of flexibility. Setting up a truly interactive shell would require a lot of work, including (but most certainly not limited to):
* splitting input commands on the pipe `|` operator and spawning a new child_process for each
* piping the TextEditor into the correct process asking for input
* piping each child_process into the next and the final child_process back to the command-output-view
* piping each child_process's stderr directly to the command-output-view
* checking for file redirection operators `>` and `>>` to determine the final location of output (the command-output-view or a file somewhere)
* and probably more than one thing that I'm forgetting right now.

While I would love to see this project reach that level, this is no simple task. I've considered attempting it, but I've found that my knowledge of Node streams is somewhat limited. If anyone feels that they can do all of this then here's my +1, otherwise if enough interest is shown, but no one wants to attempt it, I may renew my effort and take a crack at it myself.

**Comment by braver** [comment]
The current implementation of the terminal doesn't allow some of the more advanced features of a full fledged interactive terminal. A bug in a node module has prevented moving toward a more advanced terminal. For the foreseeable future we're sticking to this. If a more advanced implementation happens your wish may be granted, but for now we're closing this and similar issues as beyond the current scope.

You can watch #3 for any progress on this, but it's not in the cards for now.
