### ISSUE TITLE
it doesn't see my rvm installed ruby/gems

### ISSUE THREAD

**Issue by blazeeboy** [thedaniel/terminal-panel#43]
if command not found it just rail silently i tried `rspec` and it doesn't return anything.

`which ruby` returned `/usr/bin/ruby` 

`rvm` is not here at all

and i tried to copy from the panel now and it just doesn't work.

and i think you should handle the up and down arrows  to traverse the bash history.

when i executed `irb` it return a test `Switching to inspect mode.` and i can't write anything  except after killing it.

**Comment by braver** [comment]
@blazeeboy you mention a number of possible issues in your message. Could you narrow this down to a single issue, describing what you expect to happen and how terminal-panel fails to meet that expectation?

**Comment by mbajur** [comment]
As far as there is no any new activity from blazeeboy in here, i think i'm gonna describe my issue because i believe it's the same thing. 

Basically, i'm using RVM to handle my ruby versions and it seems that terminal-panel can't see that i'm using RVM. Thus, i'm not able to, for example, use `> RVM` in terminal-panel (it does not returns anything, just the icon is red [i believe it indicates an error/command not found?]) while in a regular terminal shell, it returns some default help message for RVM. It means that session triggered in terminal-panel does not know about RVM at all.

I woud love to suggest what can be wrong in here but all those shell/bashrc things are a bit magiciall to me so i hope any more well-versed person will help us in here :)

**Comment by braver** [comment]
What's important to know about this package is that it isn't a full shell, but instead runs your command through exec. This means that it can't provide any interactivity, and that things like your bash profile aren't considered. 

Most of the issues for terminal-package stem from this limitation. Watch #3 if you want to know if anything changes in this regard.
